config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id' ,to: "tasks#show", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAsistenteTareas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tareas</h1>
<ul>
  <% @tasks.each do |task| %>
   <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

app/views/tasks/show.html.erb
<h1>Tarea : <%= @task.title %></h1>

<h3>Description</h3>
<p><%= @task.details %></p>

<h3>Completed</h3>
<p><%= @task.completed? ? 'esta lista' : 'No esta lista' %></p>

<%= link_to 'Regresar a la lista de Tareas', tasks_path %>